"""
Base de connaissances sur les lignes de fiches de paie françaises.
Chaque entrée contient une explication pédagogique claire.
"""

# Dictionnaire des libellés connus avec leurs explications
PAYSLIP_KNOWLEDGE = {
    # === RÉMUNÉRATION ===
    "SALAIRE DE BASE": {
        "type": "salaire",
        "categorie": "remuneration",
        "explication": "C'est votre salaire mensuel fixe, calculé à partir de votre taux horaire multiplié par le nombre d'heures du mois (151,67h pour un temps plein à 35h/semaine).",
        "a_quoi_ca_sert": "C'est la base de votre rémunération, sur laquelle sont calculées la plupart des cotisations.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "SAL MIN CONV": {
        "type": "salaire",
        "categorie": "remuneration",
        "explication": "Salaire minimum conventionnel : c'est le minimum que votre convention collective impose pour votre poste et coefficient. Votre salaire de base doit être au moins égal à ce montant.",
        "a_quoi_ca_sert": "Référence pour vérifier que votre salaire respecte les minimums de la convention collective.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "COMPL SAL IND": {
        "type": "salaire",
        "categorie": "remuneration",
        "explication": "Complément de salaire individuel : c'est la différence entre votre salaire de base et le minimum conventionnel. Cela montre que votre employeur vous paie au-dessus du minimum.",
        "a_quoi_ca_sert": "Garantir que votre rémunération totale atteint au moins le niveau de base prévu.",
        "qui_paie": "employeur",
        "obligatoire": False,
    },
    "HRES AU TAUX NORMAL": {
        "type": "salaire",
        "categorie": "remuneration",
        "explication": "Heures travaillées au taux horaire normal. Le nombre d'heures est multiplié par votre taux horaire de base.",
        "a_quoi_ca_sert": "Rémunération des heures de travail effectuées dans le mois.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "HRES SUPPL. A 125%": {
        "type": "salaire",
        "categorie": "remuneration",
        "explication": "Heures supplémentaires majorées à 125% : ce sont les heures travaillées au-delà de 35h/semaine. Elles sont payées 25% de plus que le taux normal.",
        "a_quoi_ca_sert": "Rémunérer le travail au-delà de la durée légale avec une majoration de 25%.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "BONUS MENSUEL": {
        "type": "prime",
        "categorie": "primes",
        "explication": "Prime de performance mensuelle versée en fonction de critères définis (qualité, productivité, objectifs atteints, etc.).",
        "a_quoi_ca_sert": "Récompenser la performance individuelle ou collective du mois.",
        "qui_paie": "employeur",
        "obligatoire": False,
    },

    # === ABSENCES ET CONGÉS ===
    "ABS CONGES PAYES": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Déduction pour jours de congés payés pris. Le montant est retiré du salaire de base car ces jours ne sont pas 'travaillés' au sens strict.",
        "a_quoi_ca_sert": "Retirer les jours de congés du calcul du salaire de base (ils sont compensés par l'indemnité de congés payés).",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "IND CONGES PAYES": {
        "type": "indemnite",
        "categorie": "remuneration",
        "explication": "Indemnité de congés payés : c'est le montant versé pour compenser les jours de congés. Calculée soit au maintien de salaire, soit à 10% du brut (la méthode la plus avantageuse pour le salarié est retenue).",
        "a_quoi_ca_sert": "Vous rémunérer pendant vos congés payés.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "ABS. NON AUTORISEE": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Absence non autorisée : retenue sur salaire pour une absence qui n'a pas été justifiée ou autorisée par l'employeur.",
        "a_quoi_ca_sert": "Déduire du salaire les heures/jours d'absence non justifiée.",
        "qui_paie": "salarié (retenue)",
        "obligatoire": True,
    },
    "ABS. AUTOR.NON PAYEE": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Absence autorisée non payée : l'absence a été validée par l'employeur mais elle n'est pas rémunérée (ex: convenance personnelle).",
        "a_quoi_ca_sert": "Déduire du salaire une absence accordée mais sans maintien de rémunération.",
        "qui_paie": "salarié (retenue)",
        "obligatoire": True,
    },
    "ABS. JOUR FERIE": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Déduction liée à un jour férié. Le montant est déduit puis compensé par l'indemnité correspondante.",
        "a_quoi_ca_sert": "Traitement comptable des jours fériés (débit/crédit).",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "IND. JOUR FERIE": {
        "type": "indemnite",
        "categorie": "remuneration",
        "explication": "Indemnité de jour férié : compensation versée pour le jour férié chômé.",
        "a_quoi_ca_sert": "Maintenir votre salaire les jours fériés non travaillés.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "ABSENCE DIVERS": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Déduction pour une absence de nature diverse (délégation, formation, etc.). Généralement compensée par une indemnité correspondante.",
        "a_quoi_ca_sert": "Retirer comptablement les heures d'absence du salaire de base.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "INDEMNITE DIVERS": {
        "type": "indemnite",
        "categorie": "remuneration",
        "explication": "Indemnité compensant une absence diverse. Maintient la rémunération pendant l'absence.",
        "a_quoi_ca_sert": "Compenser la retenue liée à l'absence diverse.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "ABSENCE H.MALADIE": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Retenue pour absence maladie (hors maintien de salaire). Le salarié percevra des indemnités journalières de la Sécurité sociale.",
        "a_quoi_ca_sert": "Déduire les jours non travaillés pour cause de maladie.",
        "qui_paie": "salarié (retenue) / CPAM (indemnités)",
        "obligatoire": True,
    },
    "REGUL CP.ANTICIPES": {
        "type": "regularisation",
        "categorie": "remuneration",
        "explication": "Régularisation de congés payés anticipés : ajustement lié à des congés pris par anticipation avant leur acquisition complète.",
        "a_quoi_ca_sert": "Corriger un écart entre congés pris et congés acquis.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },

    # === DÉLÉGATION / CSE ===
    "ABS. DELEGATION CSE": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Heures de délégation CSE (Comité Social et Économique) : temps passé par un élu du personnel pour ses activités de représentation. Déduit puis compensé.",
        "a_quoi_ca_sert": "Traitement comptable des heures de délégation syndicale/CSE.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "IND.DELEGATION CSE": {
        "type": "indemnite",
        "categorie": "remuneration",
        "explication": "Indemnité de délégation CSE : compensation des heures de délégation. Le salarié est payé normalement pendant ses heures de représentation.",
        "a_quoi_ca_sert": "Maintenir la rémunération pendant les activités de représentation du personnel.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "ABS. DELEGATION": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Heures de délégation pour activités de représentation du personnel (hors CSE spécifiquement).",
        "a_quoi_ca_sert": "Traitement comptable des heures de délégation.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "IND. DELEGATION": {
        "type": "indemnite",
        "categorie": "remuneration",
        "explication": "Indemnité compensant les heures de délégation.",
        "a_quoi_ca_sert": "Maintenir le salaire pendant les activités de représentation.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "ABS ECO ET SYNDICAL": {
        "type": "absence",
        "categorie": "remuneration",
        "explication": "Absence pour activité économique et syndicale (réunions syndicales, négociations, etc.).",
        "a_quoi_ca_sert": "Traitement comptable des heures consacrées aux activités syndicales.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },
    "IND ECO ET SYNDICAL": {
        "type": "indemnite",
        "categorie": "remuneration",
        "explication": "Indemnité compensant les heures d'absence pour activité économique et syndicale.",
        "a_quoi_ca_sert": "Maintenir le salaire pendant les activités syndicales.",
        "qui_paie": "employeur",
        "obligatoire": True,
    },

    # === PRIMES SPÉCIALES ===
    "PR.PART.VALEUR NS/NI": {
        "type": "prime",
        "categorie": "primes",
        "explication": "Prime de partage de la valeur (anciennement 'prime Macron') : prime exceptionnelle non soumise à cotisations sociales (NS) et non imposable (NI) sous certaines conditions.",
        "a_quoi_ca_sert": "Redistribuer une partie de la valeur créée par l'entreprise aux salariés, avec un régime fiscal avantageux.",
        "qui_paie": "employeur",
        "obligatoire": False,
    },

    # === COTISATIONS SANTÉ ===
    "SECURITE SOCIALE - MALADIE MATERNITE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation patronale pour l'assurance maladie-maternité. Finance les remboursements de soins médicaux, les indemnités maternité/paternité et les arrêts maladie.",
        "a_quoi_ca_sert": "Financer la Sécurité sociale : remboursement des soins, arrêts maladie, congés maternité/paternité.",
        "qui_paie": "employeur uniquement (depuis 2018, la part salariale a été supprimée)",
        "obligatoire": True,
    },
    "PREVOYANCE INCAPACITE INVALIDITE DECES TA": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation de prévoyance sur la Tranche A (jusqu'au plafond SS). Couvre les risques d'incapacité de travail, d'invalidité et de décès au-delà de ce que couvre la Sécurité sociale.",
        "a_quoi_ca_sert": "Garantir un revenu complémentaire en cas d'arrêt de travail prolongé, d'invalidité, ou verser un capital aux ayants droit en cas de décès.",
        "qui_paie": "les deux (salarié + employeur)",
        "obligatoire": True,
    },
    "COMPLEMENTAIRE INCAPACITE INVALIDITE DECES TA": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation complémentaire de prévoyance (incapacité, invalidité, décès) sur Tranche A. Même rôle que la prévoyance, avec le régime complémentaire.",
        "a_quoi_ca_sert": "Assurer un complément de revenus en cas d'incapacité, invalidité ou décès.",
        "qui_paie": "les deux (salarié + employeur)",
        "obligatoire": True,
    },
    "COMPLEMENTAIRE SANTE OBLIGATOIRE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation pour la mutuelle d'entreprise obligatoire. Depuis 2016, tout employeur doit proposer une complémentaire santé à ses salariés et en financer au moins 50%.",
        "a_quoi_ca_sert": "Compléter les remboursements de la Sécurité sociale pour vos frais de santé (médecin, dentiste, optique, hospitalisation...).",
        "qui_paie": "les deux (au moins 50% employeur, le reste salarié)",
        "obligatoire": True,
    },
    "COMPLEMENTAIRE SANTE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation pour la mutuelle d'entreprise (complémentaire santé). Complète les remboursements de la Sécurité sociale.",
        "a_quoi_ca_sert": "Compléter les remboursements de soins au-delà de la part Sécurité sociale.",
        "qui_paie": "les deux (salarié + employeur)",
        "obligatoire": True,
    },
    "ACCIDENTS DU TRAVAIL-MALADIES PROFESSIONNELLES": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation patronale AT/MP. Le taux dépend du secteur d'activité et de la sinistralité de l'entreprise. Finance la prise en charge des accidents du travail et maladies professionnelles.",
        "a_quoi_ca_sert": "Financer l'indemnisation des salariés victimes d'accidents du travail ou de maladies professionnelles.",
        "qui_paie": "employeur uniquement",
        "obligatoire": True,
    },

    # === COTISATIONS RETRAITE ===
    "SECURITE SOCIALE PLAFONNEE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation retraite de base plafonnée (sur la partie du salaire jusqu'au plafond de la Sécurité sociale : ~3 864€/mois en 2024). Finance votre retraite de base du régime général.",
        "a_quoi_ca_sert": "Constituer vos droits à la retraite de base versée par la Sécurité sociale.",
        "qui_paie": "les deux (salarié ~6,90% + employeur ~8,55%)",
        "obligatoire": True,
    },
    "SECURITE SOCIALE DEPLAFONNEE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation retraite de base déplafonnée : calculée sur la totalité du salaire brut (sans plafond). Complète la cotisation plafonnée.",
        "a_quoi_ca_sert": "Contribuer au financement du régime de retraite de base sur l'ensemble du salaire.",
        "qui_paie": "les deux (salarié ~0,40% + employeur ~2,02%)",
        "obligatoire": True,
    },
    "RETRAITE COMPLEMENTAIRE ET CEG TRANCHE 1": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation retraite complémentaire AGIRC-ARRCO + Contribution d'Équilibre Général (CEG) sur la Tranche 1 (jusqu'au plafond SS). S'ajoute à la retraite de base.",
        "a_quoi_ca_sert": "Constituer vos droits à la retraite complémentaire (points AGIRC-ARRCO), en plus de la retraite de base.",
        "qui_paie": "les deux (salarié ~4,01% + employeur ~6,01%)",
        "obligatoire": True,
    },
    "COMPLEMENTAIRE TRANCHE 1": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation retraite complémentaire AGIRC-ARRCO Tranche 1 (ancien libellé, avant fusion avec CEG). Finance votre retraite complémentaire.",
        "a_quoi_ca_sert": "Constituer vos droits à la retraite complémentaire obligatoire.",
        "qui_paie": "les deux (salarié + employeur)",
        "obligatoire": True,
    },

    # === FAMILLE / CHÔMAGE ===
    "FAMILLE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation patronale d'allocations familiales. Finance la CAF (allocations familiales, APL, prime d'activité, etc.).",
        "a_quoi_ca_sert": "Financer les prestations familiales versées par la CAF à toutes les familles.",
        "qui_paie": "employeur uniquement",
        "obligatoire": True,
    },
    "ASSURANCE CHOMAGE": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisation patronale d'assurance chômage (depuis 2018, la part salariale a été supprimée). Finance les allocations chômage (ARE) versées par Pôle Emploi / France Travail.",
        "a_quoi_ca_sert": "Garantir un revenu de remplacement en cas de perte involontaire d'emploi.",
        "qui_paie": "employeur uniquement (depuis oct. 2018)",
        "obligatoire": True,
    },

    # === CSG / CRDS ===
    "CSG DEDUCTIBLE DE L'IMPOT SUR LE REVENU": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Contribution Sociale Généralisée (part déductible) : prélevée sur 98,25% du salaire brut. Cette part (6,80%) est déductible de votre revenu imposable, donc elle réduit votre impôt sur le revenu.",
        "a_quoi_ca_sert": "Financer la Sécurité sociale (maladie, famille, vieillesse, handicap). La part déductible allège votre impôt.",
        "qui_paie": "salarié uniquement",
        "obligatoire": True,
    },
    "CSG/CRDS NON DEDUCTIBLES DE L'IMPOT SUR LE REVENU": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "CSG non déductible (2,40%) + CRDS (0,50%) : ces contributions ne réduisent PAS votre revenu imposable. Elles sont 'en plus' de votre impôt.",
        "a_quoi_ca_sert": "Financer la Sécurité sociale (CSG) et rembourser la dette sociale (CRDS). Non déductibles = pas d'avantage fiscal.",
        "qui_paie": "salarié uniquement",
        "obligatoire": True,
    },
    "CSG/CRDS SUR LES REVENUS NON IMPOSABLES": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "CSG/CRDS calculée sur les revenus exonérés d'impôt (comme les heures supplémentaires exonérées). Même si ces revenus ne sont pas imposables, ils restent soumis à la CSG/CRDS.",
        "a_quoi_ca_sert": "Appliquer la CSG/CRDS même sur les revenus bénéficiant d'une exonération fiscale.",
        "qui_paie": "salarié uniquement",
        "obligatoire": True,
    },

    # === COTISATIONS DIVERSES ===
    "COTISATIONS STATUTAIRES": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Cotisations prévues par la convention collective ou les accords d'entreprise (ex: contribution au dialogue social, formation, etc.).",
        "a_quoi_ca_sert": "Financer des dispositifs spécifiques à votre branche professionnelle.",
        "qui_paie": "variable selon la cotisation",
        "obligatoire": True,
    },
    "AUTRES CHARGES DUES PAR L'EMPLOYEUR": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Ensemble de contributions patronales diverses : formation professionnelle, taxe d'apprentissage, participation à l'effort de construction, etc.",
        "a_quoi_ca_sert": "Financer la formation professionnelle, l'apprentissage et le logement.",
        "qui_paie": "employeur uniquement",
        "obligatoire": True,
    },
    "AUTRES CONTRIBUTIONS DUES PAR L'EMPLOYEUR": {
        "type": "cotisation",
        "categorie": "cotisations",
        "explication": "Contributions patronales diverses : formation professionnelle, taxe d'apprentissage, FNAL, etc.",
        "a_quoi_ca_sert": "Financer la formation, l'apprentissage et le logement.",
        "qui_paie": "employeur uniquement",
        "obligatoire": True,
    },

    # === EXONÉRATIONS ===
    "EXONERATIONS ET ALLEGEMENTS DE COTISATIONS": {
        "type": "exoneration",
        "categorie": "cotisations",
        "explication": "Réductions de cotisations patronales accordées par l'État (réduction Fillon, exonération heures sup, etc.). Cela réduit le coût du travail pour l'employeur.",
        "a_quoi_ca_sert": "Réduire le coût du travail, notamment pour les salaires proches du SMIC.",
        "qui_paie": "réduction pour l'employeur",
        "obligatoire": True,
    },
    "EXONERATIONS DE COTISATIONS SALARIALES": {
        "type": "exoneration",
        "categorie": "cotisations",
        "explication": "Exonération de cotisations salariales, typiquement sur les heures supplémentaires.",
        "a_quoi_ca_sert": "Augmenter le net perçu sur les heures supplémentaires.",
        "qui_paie": "avantage pour le salarié",
        "obligatoire": True,
    },
    "EXONERATIONS DE COTISATIONS EMPLOYEUR": {
        "type": "exoneration",
        "categorie": "cotisations",
        "explication": "Allègements de cotisations patronales (réduction Fillon, etc.).",
        "a_quoi_ca_sert": "Réduire le coût du travail pour l'employeur.",
        "qui_paie": "réduction pour l'employeur",
        "obligatoire": True,
    },

    # === INDEMNITÉS NON SOUMISES ===
    "TRANSPORT PROVINCE": {
        "type": "indemnite",
        "categorie": "indemnites_non_soumises",
        "explication": "Participation de l'employeur aux frais de transport en province. Non soumise à cotisations sociales.",
        "a_quoi_ca_sert": "Participer à vos frais de déplacement domicile-travail.",
        "qui_paie": "employeur",
        "obligatoire": False,
    },
    "IND.FORF.TELETRAV.NS": {
        "type": "indemnite",
        "categorie": "indemnites_non_soumises",
        "explication": "Indemnité forfaitaire de télétravail non soumise à cotisations. Compense les frais liés au travail à domicile (électricité, internet, etc.).",
        "a_quoi_ca_sert": "Rembourser vos frais professionnels liés au télétravail.",
        "qui_paie": "employeur",
        "obligatoire": False,
    },
    "IND.TELETRVAIL NS NI": {
        "type": "indemnite",
        "categorie": "indemnites_non_soumises",
        "explication": "Indemnité de télétravail non soumise à cotisations (NS) et non imposable (NI). Compense les frais du travail à domicile.",
        "a_quoi_ca_sert": "Rembourser vos frais professionnels de télétravail, en franchise de cotisations et d'impôt.",
        "qui_paie": "employeur",
        "obligatoire": False,
    },

    # === RETENUES ===
    "RET.TITRE REPAS": {
        "type": "retenue",
        "categorie": "retenues",
        "explication": "Retenue pour titres-restaurant : c'est votre part salariale du coût des tickets restaurant. L'employeur finance l'autre partie (visible dans la colonne employeur).",
        "a_quoi_ca_sert": "Financer votre part des titres-restaurant. L'employeur paie entre 50% et 60% de la valeur faciale.",
        "qui_paie": "les deux (salarié + employeur)",
        "obligatoire": False,
    },
    "FR.SANTE IMP.": {
        "type": "retenue",
        "categorie": "retenues",
        "explication": "Part patronale de la mutuelle santé réintégrée dans le revenu imposable. Ce n'est pas une retenue réelle mais un ajout à votre base imposable : la part employeur de la mutuelle est considérée comme un avantage imposable.",
        "a_quoi_ca_sert": "Ajouter à votre revenu imposable la contribution employeur à la mutuelle (car c'est un avantage en nature fiscal).",
        "qui_paie": "impact fiscal pour le salarié",
        "obligatoire": True,
    },
    "IMPOT SUR LE REVENU PRELEVE": {
        "type": "impot",
        "categorie": "retenues",
        "explication": "Prélèvement à la source (PAS) de l'impôt sur le revenu. Le taux est soit personnalisé (basé sur votre dernière déclaration) soit non personnalisé (taux neutre).",
        "a_quoi_ca_sert": "Payer votre impôt sur le revenu directement chaque mois, au lieu d'un paiement annuel.",
        "qui_paie": "salarié (prélevé par l'employeur pour le compte de l'État)",
        "obligatoire": True,
    },
    "OPPOSITION 2": {
        "type": "retenue",
        "categorie": "retenues",
        "explication": "Saisie sur salaire (opposition) : retenue ordonnée par un tribunal ou un créancier. Une partie de votre salaire est prélevée pour rembourser une dette.",
        "a_quoi_ca_sert": "Rembourser une dette conformément à une décision de justice ou une procédure de saisie.",
        "qui_paie": "salarié (retenue obligatoire)",
        "obligatoire": True,
    },

    # === HEURES SUPPLÉMENTAIRES EXONÉRÉES ===
    "HS EXO SOC.": {
        "type": "information",
        "categorie": "informations",
        "explication": "Montant des heures supplémentaires exonérées de cotisations sociales salariales. Depuis 2019, les HS sont exonérées de certaines cotisations.",
        "a_quoi_ca_sert": "Information sur le montant d'heures sup bénéficiant d'une exonération sociale.",
        "qui_paie": "avantage pour le salarié",
        "obligatoire": True,
    },
    "HS EXO": {
        "type": "information",
        "categorie": "informations",
        "explication": "Montant des heures supplémentaires exonérées de cotisations.",
        "a_quoi_ca_sert": "Information sur les HS exonérées.",
        "qui_paie": "avantage pour le salarié",
        "obligatoire": True,
    },
}

# Patterns pour reconnaître des libellés similaires
LABEL_PATTERNS = {
    r"SALAIRE DE BASE": "SALAIRE DE BASE",
    r"SAL MIN CONV": "SAL MIN CONV",
    r"COMPL SAL IND": "COMPL SAL IND",
    r"HRES? (AU )?TAUX NORMAL": "HRES AU TAUX NORMAL",
    r"HRES? SUPPL.*125%": "HRES SUPPL. A 125%",
    r"BONUS MENSUEL": "BONUS MENSUEL",
    r"ABS[\. ]*CONGES PAYES": "ABS CONGES PAYES",
    r"IND[\. ]*CONGES PAYES": "IND CONGES PAYES",
    r"ABS[\. ]*NON AUTORISEE": "ABS. NON AUTORISEE",
    r"ABS[\. ]*AUTOR[\. ]*NON PAYEE": "ABS. AUTOR.NON PAYEE",
    r"ABS[\. ]*JOUR FERIE": "ABS. JOUR FERIE",
    r"IND[\. ]*JOUR FERIE": "IND. JOUR FERIE",
    r"ABSENCE DIVERS": "ABSENCE DIVERS",
    r"INDEMNITE DIVERS": "INDEMNITE DIVERS",
    r"ABSENCE H[\. ]*MALADIE": "ABSENCE H.MALADIE",
    r"REGUL CP": "REGUL CP.ANTICIPES",
    r"ABS[\. ]*DELEGATION CSE": "ABS. DELEGATION CSE",
    r"IND[\. ]*DELEGATION CSE": "IND.DELEGATION CSE",
    r"ABS[\. ]*DELEGATION(?! CSE)": "ABS. DELEGATION",
    r"IND[\. ]*DELEGATION(?! CSE)": "IND. DELEGATION",
    r"ABS ECO ET SYNDICAL": "ABS ECO ET SYNDICAL",
    r"IND ECO ET SYNDICAL": "IND ECO ET SYNDICAL",
    r"PR[\. ]*PART[\. ]*VALEUR": "PR.PART.VALEUR NS/NI",
    r"SECURITE SOCIALE.*MALADIE": "SECURITE SOCIALE - MALADIE MATERNITE",
    r"PREVOYANCE INCAPACITE": "PREVOYANCE INCAPACITE INVALIDITE DECES TA",
    r"COMPLEMENTAIRE INCAPACITE": "COMPLEMENTAIRE INCAPACITE INVALIDITE DECES TA",
    r"COMPLEMENTAIRE SANTE OBLIGATOIRE": "COMPLEMENTAIRE SANTE OBLIGATOIRE",
    r"COMPLEMENTAIRE SANTE(?! OBLIGATOIRE)": "COMPLEMENTAIRE SANTE",
    r"ACCIDENTS DU TRAVAIL": "ACCIDENTS DU TRAVAIL-MALADIES PROFESSIONNELLES",
    r"SECURITE SOCIALE PLAFONNEE": "SECURITE SOCIALE PLAFONNEE",
    r"SECURITE SOCIALE DEPLAFONNEE": "SECURITE SOCIALE DEPLAFONNEE",
    r"RETRAITE COMPLEMENTAIRE.*CEG.*TRANCHE 1": "RETRAITE COMPLEMENTAIRE ET CEG TRANCHE 1",
    r"COMPLEMENTAIRE TRANCHE 1": "COMPLEMENTAIRE TRANCHE 1",
    r"^FAMILLE$": "FAMILLE",
    r"ASSURANCE CHOMAGE": "ASSURANCE CHOMAGE",
    r"CSG DEDUCTIBLE": "CSG DEDUCTIBLE DE L'IMPOT SUR LE REVENU",
    r"CSG.CRDS NON DEDUCTIBLE": "CSG/CRDS NON DEDUCTIBLES DE L'IMPOT SUR LE REVENU",
    r"CSG.CRDS SUR LES REVENUS NON": "CSG/CRDS SUR LES REVENUS NON IMPOSABLES",
    r"COTISATIONS STATUTAIRES": "COTISATIONS STATUTAIRES",
    r"AUTRES CHARGES DUES": "AUTRES CHARGES DUES PAR L'EMPLOYEUR",
    r"AUTRES CONTRIBUTIONS DUES": "AUTRES CONTRIBUTIONS DUES PAR L'EMPLOYEUR",
    r"EXONERATIONS ET ALLEGEMENTS": "EXONERATIONS ET ALLEGEMENTS DE COTISATIONS",
    r"EXONERATIONS DE COTISATIONS SALARIALES": "EXONERATIONS DE COTISATIONS SALARIALES",
    r"EXONERATIONS DE COTISATIONS EMPLOYEUR": "EXONERATIONS DE COTISATIONS EMPLOYEUR",
    r"TRANSPORT PROVINCE": "TRANSPORT PROVINCE",
    r"IND[\. ]*FORF[\. ]*TELETRAV": "IND.FORF.TELETRAV.NS",
    r"IND[\. ]*TELETRVAIL": "IND.TELETRVAIL NS NI",
    r"RET[\. ]*TITRE REPAS": "RET.TITRE REPAS",
    r"FR[\. ]*SANTE IMP": "FR.SANTE IMP.",
    r"IMPOT SUR LE REVENU": "IMPOT SUR LE REVENU PRELEVE",
    r"OPPOSITION": "OPPOSITION 2",
    r"HS EXO SOC": "HS EXO SOC.",
    r"HS EXO(?! SOC)": "HS EXO",
}
